---

sudo: required
dist: xenial

language: python
python: "3.5"

install:
  # Install ansible
  - pip install ansible
  - ansible --version

  # install yamllint
  - pip install yamllint

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Linting for YAML correctness
  - yamllint .
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
